### ISSUE TITLE
How can I build on Latest MacOS(10.9.5)

### ISSUE THREAD

**Issue by SanghunHeo** [ofZach/algo2012#1]
Hi Zach
I want to build it on my mac. But how can I build on Latest MacOS(10.9.5).
When I try to build the project with Latest Xcode(6.0), it become fail.
Thank you.

**Comment by ofZach** [comment]
this is the latest OF that works with xcode 6: 
http://openframeworks.cc/download/

**Comment by SanghunHeo** [comment]
Thx, I tried with it already.
But still build failed.
Below is my xcode screenshot, you may can check error messages and build settings.
![image](https://cloud.githubusercontent.com/assets/2508048/4334129/cbd9290e-3fe9-11e4-81bf-fe6d24a4ef39.png)
Thank you.

**Comment by ofZach** [comment]
the project file is missing some frameworks since it's older...   either look for the framework difference and fix it in the project, or remake the projects in the newest OF.

**Comment by SanghunHeo** [comment]
Thank you Zach.
I just success build with new project generated with projectGenerator.
But is there any automatic way to fix all projects?
If not, should I make old environment like osX lion with old xcode to make build success like charm?

**Comment by ofZach** [comment]
sorry there is no automated way to do this with the current PG tool

**Comment by SanghunHeo** [comment]
Ok I understand, Thank you for your quick response :+1:
